// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Authorization.V1
{

    [OutputType]
    public sealed class ResourceRule
    {
        /// <summary>
        /// APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of the enumerated resources in any API group will be allowed.  "*" means all.
        /// </summary>
        public readonly ImmutableArray<string> ApiGroups;
        /// <summary>
        /// ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.  "*" means all.
        /// </summary>
        public readonly ImmutableArray<string> ResourceNames;
        /// <summary>
        /// Resources is a list of resources this rule applies to.  "*" means all in the specified apiGroups.
        ///  "*/foo" represents the subresource 'foo' for all resources in the specified apiGroups.
        /// </summary>
        public readonly ImmutableArray<string> Resources;
        /// <summary>
        /// Verb is a list of kubernetes resource API verbs, like: get, list, watch, create, update, delete, proxy.  "*" means all.
        /// </summary>
        public readonly ImmutableArray<string> Verbs;

        [OutputConstructor]
        private ResourceRule(
            ImmutableArray<string> apiGroups,

            ImmutableArray<string> resourceNames,

            ImmutableArray<string> resources,

            ImmutableArray<string> verbs)
        {
            ApiGroups = apiGroups;
            ResourceNames = resourceNames;
            Resources = resources;
            Verbs = verbs;
        }
    }
}
