// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Scheduling.V1Alpha3
{

    /// <summary>
    /// CompositeDisruptionMode defines how individual entities within a composite pod group can be disrupted. Exactly one mode must be set.
    /// </summary>
    [OutputType]
    public sealed class CompositeDisruptionMode
    {
        /// <summary>
        /// all specifies that all children groups can only be disrupted together.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Scheduling.V1Alpha3.AllCompositeDisruptionMode All;
        /// <summary>
        /// single specifies that children groups can be disrupted independently from each other.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Scheduling.V1Alpha3.SingleCompositeDisruptionMode Single;

        [OutputConstructor]
        private CompositeDisruptionMode(
            Pulumi.Kubernetes.Types.Outputs.Scheduling.V1Alpha3.AllCompositeDisruptionMode all,

            Pulumi.Kubernetes.Types.Outputs.Scheduling.V1Alpha3.SingleCompositeDisruptionMode single)
        {
            All = all;
            Single = single;
        }
    }
}
