// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.scheduling.v1beta1.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.kubernetes.meta.v1.outputs.Condition;
import com.pulumi.kubernetes.scheduling.v1beta1.outputs.PodGroupResourceClaimStatus;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class PodGroupStatus {
    /**
     * @return conditions represent the latest observations of the PodGroup&#39;s state.
     * 
     * Known condition types: - &#34;PodGroupInitiallyScheduled&#34;: Indicates whether the scheduling requirement has been satisfied. Once this condition transitions to True, it serves as a terminal state and will never revert to False, even if pods are subsequently evicted and group constraints are no longer met. - &#34;DisruptionTarget&#34;: Indicates whether the PodGroup is about to be terminated
     *   due to disruption such as preemption.
     * 
     * Known reasons for the PodGroupInitiallyScheduled condition: - &#34;Unschedulable&#34;: The PodGroup cannot be scheduled due to resource constraints,
     *   affinity/anti-affinity rules, or insufficient capacity for the gang.
     * - &#34;SchedulerError&#34;: The PodGroup cannot be scheduled due to some internal error
     *   that happened during scheduling, for example due to nodeAffinity parsing errors.
     * 
     * Known reasons for the DisruptionTarget condition: - &#34;PreemptionByScheduler&#34;: The PodGroup was preempted by the scheduler to make room for
     *   higher-priority PodGroups or Pods.
     * 
     */
    private @Nullable List<Condition> conditions;
    /**
     * @return resourceClaimStatuses is status of resource claims.
     * 
     */
    private @Nullable List<PodGroupResourceClaimStatus> resourceClaimStatuses;

    private PodGroupStatus() {}
    /**
     * @return conditions represent the latest observations of the PodGroup&#39;s state.
     * 
     * Known condition types: - &#34;PodGroupInitiallyScheduled&#34;: Indicates whether the scheduling requirement has been satisfied. Once this condition transitions to True, it serves as a terminal state and will never revert to False, even if pods are subsequently evicted and group constraints are no longer met. - &#34;DisruptionTarget&#34;: Indicates whether the PodGroup is about to be terminated
     *   due to disruption such as preemption.
     * 
     * Known reasons for the PodGroupInitiallyScheduled condition: - &#34;Unschedulable&#34;: The PodGroup cannot be scheduled due to resource constraints,
     *   affinity/anti-affinity rules, or insufficient capacity for the gang.
     * - &#34;SchedulerError&#34;: The PodGroup cannot be scheduled due to some internal error
     *   that happened during scheduling, for example due to nodeAffinity parsing errors.
     * 
     * Known reasons for the DisruptionTarget condition: - &#34;PreemptionByScheduler&#34;: The PodGroup was preempted by the scheduler to make room for
     *   higher-priority PodGroups or Pods.
     * 
     */
    public List<Condition> conditions() {
        return this.conditions == null ? List.of() : this.conditions;
    }
    /**
     * @return resourceClaimStatuses is status of resource claims.
     * 
     */
    public List<PodGroupResourceClaimStatus> resourceClaimStatuses() {
        return this.resourceClaimStatuses == null ? List.of() : this.resourceClaimStatuses;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PodGroupStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<Condition> conditions;
        private @Nullable List<PodGroupResourceClaimStatus> resourceClaimStatuses;
        public Builder() {}
        public Builder(PodGroupStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditions = defaults.conditions;
    	      this.resourceClaimStatuses = defaults.resourceClaimStatuses;
        }

        @CustomType.Setter
        public Builder conditions(@Nullable List<Condition> conditions) {

            this.conditions = conditions;
            return this;
        }
        public Builder conditions(Condition... conditions) {
            return conditions(List.of(conditions));
        }
        @CustomType.Setter
        public Builder resourceClaimStatuses(@Nullable List<PodGroupResourceClaimStatus> resourceClaimStatuses) {

            this.resourceClaimStatuses = resourceClaimStatuses;
            return this;
        }
        public Builder resourceClaimStatuses(PodGroupResourceClaimStatus... resourceClaimStatuses) {
            return resourceClaimStatuses(List.of(resourceClaimStatuses));
        }
        public PodGroupStatus build() {
            final var _resultValue = new PodGroupStatus();
            _resultValue.conditions = conditions;
            _resultValue.resourceClaimStatuses = resourceClaimStatuses;
            return _resultValue;
        }
    }
}
