version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    pre-release: true
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/pulumi/cloud-ready-checks"
    labels:
      - dependencies
      - impact/no-changelog-required
