// *** WARNING: this file was generated by the Pulumi Kubernetes codegen tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Affinity is a group of affinity scheduling rules.
type Affinity struct {
	// Describes node affinity scheduling rules for the pod.
	NodeAffinity *NodeAffinity `pulumi:"nodeAffinity"`

	// Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as
	// some other pod(s)).
	PodAffinity *PodAffinity `pulumi:"podAffinity"`

	// Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node,
	// zone, etc. as some other pod(s)).
	PodAntiAffinity *PodAntiAffinity `pulumi:"podAntiAffinity"`

}

var _AffinityType = reflect.TypeOf((*Affinity)(nil)).Elem()

// AffinityInput represents an input type that resolves to a Affinity.
type AffinityInput interface {
	ElementType() reflect.Type

	ToAffinityOutput() AffinityOutput
	ToAffinityOutputWithContext(ctx context.Context) AffinityOutput
}

// AffinityArgs is a AffinityInput whose fields are all Input types.
type AffinityArgs struct {
	// Describes node affinity scheduling rules for the pod.
	NodeAffinity NodeAffinityInput `pulumi:"nodeAffinity"`

	// Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as
	// some other pod(s)).
	PodAffinity PodAffinityInput `pulumi:"podAffinity"`

	// Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node,
	// zone, etc. as some other pod(s)).
	PodAntiAffinity PodAntiAffinityInput `pulumi:"podAntiAffinity"`

}

func (a AffinityArgs) ElementType() reflect.Type {
	return _AffinityType
}

func (a AffinityArgs) ToAffinityOutput() AffinityOutput {
	return pulumi.ToOutput(a).(AffinityOutput)
}

func (a AffinityArgs) ToAffinityOutputWithContext(ctx context.Context) AffinityOutput {
	return pulumi.ToOutputWithContext(ctx, a).(AffinityOutput)
}

// AffinityOutput is an output type that resolves to a Input.
type AffinityOutput struct { *pulumi.OutputState }

func init() { pulumi.RegisterOutputType(AffinityOutput{}) }

func (AffinityOutput) ElementType() reflect.Type {
	return _AffinityType
}

func (o AffinityOutput) NodeAffinity() NodeAffinityOutput {
	return o.Apply(func(v Affinity) *NodeAffinity {
		return v.NodeAffinity
	}).(NodeAffinityOutput)
}

func (o AffinityOutput) PodAffinity() PodAffinityOutput {
	return o.Apply(func(v Affinity) *PodAffinity {
		return v.PodAffinity
	}).(PodAffinityOutput)
}

func (o AffinityOutput) PodAntiAffinity() PodAntiAffinityOutput {
	return o.Apply(func(v Affinity) *PodAntiAffinity {
		return v.PodAntiAffinity
	}).(PodAntiAffinityOutput)
}

