template: native
provider: kubernetes
lint: true
aws: true # need AWS credentials to test in EKS
gcp: true # need GCP credentials to test in GKE
pulumiVersionFile: .pulumi.version
major-version: 4
parallel: 3
toolVersions:
  go: 1.24.x
envOverride:
  PULUMI_API: app.pulumi-staging.io
  AWS_REGION: us-west-2
  PULUMI_TEST_OWNER: moolumi
  GOLANGCI_LINT_VERSION: v1.64.8
  GOOGLE_CI_SERVICE_ACCOUNT_EMAIL: pulumi-ci@pulumi-k8s-provider.iam.gserviceaccount.com
  GOOGLE_CI_WORKLOAD_IDENTITY_POOL: pulumi-ci
  GOOGLE_CI_WORKLOAD_IDENTITY_PROVIDER: pulumi-ci
  GOOGLE_PROJECT_NUMBER: 637339343727
