linters:
  enable-all: false
  enable:
    - unused
    - errcheck
    - goconst
    - gofmt
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - gosimple
  disable:
    - lll
run:
  modules-download-mode: readonly
  timeout: 10m
issues:
  exclude-dirs-use-default: true
