linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - golint
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
  disable:
    - lll
    - megacheck # Disabled due to OOM errors in golangci-lint@v1.18.0
    - staticcheck # Disabled due to OOM errors in golangci-lint@v1.18.0
