linters:
  enable-all: false
  enable:
    - unused
    - errcheck
    - goconst
    - gofmt
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - gosimple
  disable:
    - lll
run:
  skip-files:
    - schema.go
  skip-dirs:
    - provider/pkg/gen
  skip-dirs-use-default: true
  modules-download-mode: readonly
  timeout: 10m
issues:
  exclude-rules:
    path: "provider/cmd/pulumi-resource-kubernetes"
    source: "^//go:embed"
