linters:
  enable-all: false
  enable:
    - unused
    - errcheck
    - goconst
    - gofmt
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - gosimple
  disable:
    - lll
run:
  modules-download-mode: readonly
  timeout: 10m
issues:
  exclude-rules:
    # The gosec linter is overly aggressive about integer conversions.
    # Our retrier uses an unsigned int64 to represent the number of retries,
    # which is safe to convert to a signed int64 as we don't expect it to be extremely large.
    # https://github.com/securego/gosec/issues/1185
    - path: "provider/pkg/retry/retry.go"
      text: "integer overflow conversion"
