linters:
  enable-all: false
  enable:
    - unused
    - errcheck
    - goconst
    - gofmt
    - staticcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - gosimple
run:
  modules-download-mode: readonly
  timeout: 10m
issues:
  exclude-files:
    - schema.go
  exclude-dirs:
    - provider/pkg/gen