archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make k8sgen
    - make openapi_file
    - make schema
    - make k8sprovider
blobs:
  - bucket: get.pulumi.com
    folder: releases/plugins/
    ids:
      - archive
    provider: s3
    region: us-west-2
builds:
  - binary: pulumi-resource-kubernetes
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-kubernetes/
changelog:
  skip: true
release:
  disable: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
