// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.resource.v1beta2.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.kubernetes.resource.v1beta2.inputs.DeviceSubRequestPatchArgs;
import com.pulumi.kubernetes.resource.v1beta2.inputs.ExactDeviceRequestPatchArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * DeviceRequest is a request for devices required for a claim. This is typically a request for a single resource like a device, but can also ask for several identical devices. With FirstAvailable it is also possible to provide a prioritized list of requests.
 * 
 */
public final class DeviceRequestPatchArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeviceRequestPatchArgs Empty = new DeviceRequestPatchArgs();

    /**
     * Exactly specifies the details for a single request that must be met exactly for the request to be satisfied.
     * 
     * One of Exactly or FirstAvailable must be set.
     * 
     */
    @Import(name="exactly")
    private @Nullable Output<ExactDeviceRequestPatchArgs> exactly;

    /**
     * @return Exactly specifies the details for a single request that must be met exactly for the request to be satisfied.
     * 
     * One of Exactly or FirstAvailable must be set.
     * 
     */
    public Optional<Output<ExactDeviceRequestPatchArgs>> exactly() {
        return Optional.ofNullable(this.exactly);
    }

    /**
     * FirstAvailable contains subrequests, of which exactly one will be selected by the scheduler. It tries to satisfy them in the order in which they are listed here. So if there are two entries in the list, the scheduler will only check the second one if it determines that the first one can not be used.
     * 
     * DRA does not yet implement scoring, so the scheduler will select the first set of devices that satisfies all the requests in the claim. And if the requirements can be satisfied on more than one node, other scheduling features will determine which node is chosen. This means that the set of devices allocated to a claim might not be the optimal set available to the cluster. Scoring will be implemented later.
     * 
     */
    @Import(name="firstAvailable")
    private @Nullable Output<List<DeviceSubRequestPatchArgs>> firstAvailable;

    /**
     * @return FirstAvailable contains subrequests, of which exactly one will be selected by the scheduler. It tries to satisfy them in the order in which they are listed here. So if there are two entries in the list, the scheduler will only check the second one if it determines that the first one can not be used.
     * 
     * DRA does not yet implement scoring, so the scheduler will select the first set of devices that satisfies all the requests in the claim. And if the requirements can be satisfied on more than one node, other scheduling features will determine which node is chosen. This means that the set of devices allocated to a claim might not be the optimal set available to the cluster. Scoring will be implemented later.
     * 
     */
    public Optional<Output<List<DeviceSubRequestPatchArgs>>> firstAvailable() {
        return Optional.ofNullable(this.firstAvailable);
    }

    /**
     * Name can be used to reference this request in a pod.spec.containers[].resources.claims entry and in a constraint of the claim.
     * 
     * References using the name in the DeviceRequest will uniquely identify a request when the Exactly field is set. When the FirstAvailable field is set, a reference to the name of the DeviceRequest will match whatever subrequest is chosen by the scheduler.
     * 
     * Must be a DNS label.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name can be used to reference this request in a pod.spec.containers[].resources.claims entry and in a constraint of the claim.
     * 
     * References using the name in the DeviceRequest will uniquely identify a request when the Exactly field is set. When the FirstAvailable field is set, a reference to the name of the DeviceRequest will match whatever subrequest is chosen by the scheduler.
     * 
     * Must be a DNS label.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private DeviceRequestPatchArgs() {}

    private DeviceRequestPatchArgs(DeviceRequestPatchArgs $) {
        this.exactly = $.exactly;
        this.firstAvailable = $.firstAvailable;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeviceRequestPatchArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeviceRequestPatchArgs $;

        public Builder() {
            $ = new DeviceRequestPatchArgs();
        }

        public Builder(DeviceRequestPatchArgs defaults) {
            $ = new DeviceRequestPatchArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param exactly Exactly specifies the details for a single request that must be met exactly for the request to be satisfied.
         * 
         * One of Exactly or FirstAvailable must be set.
         * 
         * @return builder
         * 
         */
        public Builder exactly(@Nullable Output<ExactDeviceRequestPatchArgs> exactly) {
            $.exactly = exactly;
            return this;
        }

        /**
         * @param exactly Exactly specifies the details for a single request that must be met exactly for the request to be satisfied.
         * 
         * One of Exactly or FirstAvailable must be set.
         * 
         * @return builder
         * 
         */
        public Builder exactly(ExactDeviceRequestPatchArgs exactly) {
            return exactly(Output.of(exactly));
        }

        /**
         * @param firstAvailable FirstAvailable contains subrequests, of which exactly one will be selected by the scheduler. It tries to satisfy them in the order in which they are listed here. So if there are two entries in the list, the scheduler will only check the second one if it determines that the first one can not be used.
         * 
         * DRA does not yet implement scoring, so the scheduler will select the first set of devices that satisfies all the requests in the claim. And if the requirements can be satisfied on more than one node, other scheduling features will determine which node is chosen. This means that the set of devices allocated to a claim might not be the optimal set available to the cluster. Scoring will be implemented later.
         * 
         * @return builder
         * 
         */
        public Builder firstAvailable(@Nullable Output<List<DeviceSubRequestPatchArgs>> firstAvailable) {
            $.firstAvailable = firstAvailable;
            return this;
        }

        /**
         * @param firstAvailable FirstAvailable contains subrequests, of which exactly one will be selected by the scheduler. It tries to satisfy them in the order in which they are listed here. So if there are two entries in the list, the scheduler will only check the second one if it determines that the first one can not be used.
         * 
         * DRA does not yet implement scoring, so the scheduler will select the first set of devices that satisfies all the requests in the claim. And if the requirements can be satisfied on more than one node, other scheduling features will determine which node is chosen. This means that the set of devices allocated to a claim might not be the optimal set available to the cluster. Scoring will be implemented later.
         * 
         * @return builder
         * 
         */
        public Builder firstAvailable(List<DeviceSubRequestPatchArgs> firstAvailable) {
            return firstAvailable(Output.of(firstAvailable));
        }

        /**
         * @param firstAvailable FirstAvailable contains subrequests, of which exactly one will be selected by the scheduler. It tries to satisfy them in the order in which they are listed here. So if there are two entries in the list, the scheduler will only check the second one if it determines that the first one can not be used.
         * 
         * DRA does not yet implement scoring, so the scheduler will select the first set of devices that satisfies all the requests in the claim. And if the requirements can be satisfied on more than one node, other scheduling features will determine which node is chosen. This means that the set of devices allocated to a claim might not be the optimal set available to the cluster. Scoring will be implemented later.
         * 
         * @return builder
         * 
         */
        public Builder firstAvailable(DeviceSubRequestPatchArgs... firstAvailable) {
            return firstAvailable(List.of(firstAvailable));
        }

        /**
         * @param name Name can be used to reference this request in a pod.spec.containers[].resources.claims entry and in a constraint of the claim.
         * 
         * References using the name in the DeviceRequest will uniquely identify a request when the Exactly field is set. When the FirstAvailable field is set, a reference to the name of the DeviceRequest will match whatever subrequest is chosen by the scheduler.
         * 
         * Must be a DNS label.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name can be used to reference this request in a pod.spec.containers[].resources.claims entry and in a constraint of the claim.
         * 
         * References using the name in the DeviceRequest will uniquely identify a request when the Exactly field is set. When the FirstAvailable field is set, a reference to the name of the DeviceRequest will match whatever subrequest is chosen by the scheduler.
         * 
         * Must be a DNS label.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public DeviceRequestPatchArgs build() {
            return $;
        }
    }

}
