// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1
{

    /// <summary>
    /// ContainerStateRunning is a running state of a container.
    /// </summary>
    public class ContainerStateRunningArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Time at which the container was last (re-)started
        /// </summary>
        [Input("startedAt")]
        public Input<string>? StartedAt { get; set; }

        public ContainerStateRunningArgs()
        {
        }
    }
}
