// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1
{

    /// <summary>
    /// ContainerPort represents a network port in a single container.
    /// </summary>
    public class ContainerPortArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of port to expose on the pod's IP address. This must be a valid port number, 0 &lt; x &lt; 65536.
        /// </summary>
        [Input("containerPort", required: true)]
        public Input<int> ContainerPortValue { get; set; } = null!;

        /// <summary>
        /// What host IP to bind the external port to.
        /// </summary>
        [Input("hostIP")]
        public Input<string>? HostIP { get; set; }

        /// <summary>
        /// Number of port to expose on the host. If specified, this must be a valid port number, 0 &lt; x &lt; 65536. If HostNetwork is specified, this must match ContainerPort. Most containers do not need this.
        /// </summary>
        [Input("hostPort")]
        public Input<int>? HostPort { get; set; }

        /// <summary>
        /// If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Protocol for port. Must be UDP, TCP, or SCTP. Defaults to "TCP".
        /// 
        /// Possible enum values:
        ///  - `"SCTP"` is the SCTP protocol.
        ///  - `"TCP"` is the TCP protocol.
        ///  - `"UDP"` is the UDP protocol.
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        public ContainerPortArgs()
        {
        }
    }
}
