// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Core.V1
{

    /// <summary>
    /// PodOS defines the OS parameters of a pod.
    /// 
    /// By default Pulumi does _not_ wait for this resource to
    /// become ready when it is created or updated.
    /// 
    /// If you want Pulumi to wait for this resource to become ready, you can use the
    /// 'pulumi.com/waitFor' annotation to provide custom readiness criteria. See the
    /// documentation
    /// (http://localhost:1313/registry/packages/kubernetes/installation-configuration/#pulumicomwaitfor)
    /// for a detailed description of the values this annotation accepts.
    /// </summary>
    public class PodOSPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name is the name of the operating system. The currently supported values are linux and windows. Additional value may be defined in future and can be one of: https://github.com/opencontainers/runtime-spec/blob/master/config.md#platform-specific-configuration Clients should expect to handle additional values and treat unrecognized values in this field as os: null
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public PodOSPatchArgs()
        {
        }
        public static new PodOSPatchArgs Empty => new PodOSPatchArgs();
    }
}
