// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.resource.v1alpha3.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.kubernetes.meta.v1.outputs.ConditionPatch;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class DeviceTaintRuleStatusPatch {
    /**
     * @return Conditions provide information about the state of the DeviceTaintRule and the cluster at some point in time, in a machine-readable and human-readable format.
     * 
     * The following condition is currently defined as part of this API, more may get added: - Type: EvictionInProgress - Status: True if there are currently pods which need to be evicted, False otherwise
     *   (includes the effects which don&#39;t cause eviction).
     * - Reason: not specified, may change - Message: includes information about number of pending pods and already evicted pods
     *   in a human-readable format, updated periodically, may change
     * 
     * For `effect: None`, the condition above gets set once for each change to the spec, with the message containing information about what would happen if the effect was `NoExecute`. This feedback can be used to decide whether changing the effect to `NoExecute` will work as intended. It only gets set once to avoid having to constantly update the status.
     * 
     * Must have 8 or fewer entries.
     * 
     */
    private @Nullable List<ConditionPatch> conditions;

    private DeviceTaintRuleStatusPatch() {}
    /**
     * @return Conditions provide information about the state of the DeviceTaintRule and the cluster at some point in time, in a machine-readable and human-readable format.
     * 
     * The following condition is currently defined as part of this API, more may get added: - Type: EvictionInProgress - Status: True if there are currently pods which need to be evicted, False otherwise
     *   (includes the effects which don&#39;t cause eviction).
     * - Reason: not specified, may change - Message: includes information about number of pending pods and already evicted pods
     *   in a human-readable format, updated periodically, may change
     * 
     * For `effect: None`, the condition above gets set once for each change to the spec, with the message containing information about what would happen if the effect was `NoExecute`. This feedback can be used to decide whether changing the effect to `NoExecute` will work as intended. It only gets set once to avoid having to constantly update the status.
     * 
     * Must have 8 or fewer entries.
     * 
     */
    public List<ConditionPatch> conditions() {
        return this.conditions == null ? List.of() : this.conditions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DeviceTaintRuleStatusPatch defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<ConditionPatch> conditions;
        public Builder() {}
        public Builder(DeviceTaintRuleStatusPatch defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditions = defaults.conditions;
        }

        @CustomType.Setter
        public Builder conditions(@Nullable List<ConditionPatch> conditions) {

            this.conditions = conditions;
            return this;
        }
        public Builder conditions(ConditionPatch... conditions) {
            return conditions(List.of(conditions));
        }
        public DeviceTaintRuleStatusPatch build() {
            final var _resultValue = new DeviceTaintRuleStatusPatch();
            _resultValue.conditions = conditions;
            return _resultValue;
        }
    }
}
