// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.resource.v1alpha3.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.kubernetes.meta.v1.outputs.ConditionPatch;
import com.pulumi.kubernetes.resource.v1alpha3.outputs.PoolStatusPatch;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ResourcePoolStatusRequestStatusPatch {
    /**
     * @return Conditions provide information about the state of the request. A condition with type=Complete or type=Failed will always be set when the status is populated.
     * 
     * Known condition types: - &#34;Complete&#34;: True when the request has been processed successfully - &#34;Failed&#34;: True when the request could not be processed
     * 
     */
    private @Nullable List<ConditionPatch> conditions;
    /**
     * @return PoolCount is the total number of pools that matched the filter criteria, regardless of truncation. This helps users understand how many pools exist even when the response is truncated. A value of 0 means no pools matched the filter criteria.
     * 
     */
    private @Nullable Integer poolCount;
    /**
     * @return Pools contains the first `spec.limit` matching pools, sorted by driver then pool name. If `len(pools) &lt; poolCount`, the list was truncated. When omitted, no pools matched the request filters.
     * 
     */
    private @Nullable List<PoolStatusPatch> pools;

    private ResourcePoolStatusRequestStatusPatch() {}
    /**
     * @return Conditions provide information about the state of the request. A condition with type=Complete or type=Failed will always be set when the status is populated.
     * 
     * Known condition types: - &#34;Complete&#34;: True when the request has been processed successfully - &#34;Failed&#34;: True when the request could not be processed
     * 
     */
    public List<ConditionPatch> conditions() {
        return this.conditions == null ? List.of() : this.conditions;
    }
    /**
     * @return PoolCount is the total number of pools that matched the filter criteria, regardless of truncation. This helps users understand how many pools exist even when the response is truncated. A value of 0 means no pools matched the filter criteria.
     * 
     */
    public Optional<Integer> poolCount() {
        return Optional.ofNullable(this.poolCount);
    }
    /**
     * @return Pools contains the first `spec.limit` matching pools, sorted by driver then pool name. If `len(pools) &lt; poolCount`, the list was truncated. When omitted, no pools matched the request filters.
     * 
     */
    public List<PoolStatusPatch> pools() {
        return this.pools == null ? List.of() : this.pools;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ResourcePoolStatusRequestStatusPatch defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<ConditionPatch> conditions;
        private @Nullable Integer poolCount;
        private @Nullable List<PoolStatusPatch> pools;
        public Builder() {}
        public Builder(ResourcePoolStatusRequestStatusPatch defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditions = defaults.conditions;
    	      this.poolCount = defaults.poolCount;
    	      this.pools = defaults.pools;
        }

        @CustomType.Setter
        public Builder conditions(@Nullable List<ConditionPatch> conditions) {

            this.conditions = conditions;
            return this;
        }
        public Builder conditions(ConditionPatch... conditions) {
            return conditions(List.of(conditions));
        }
        @CustomType.Setter
        public Builder poolCount(@Nullable Integer poolCount) {

            this.poolCount = poolCount;
            return this;
        }
        @CustomType.Setter
        public Builder pools(@Nullable List<PoolStatusPatch> pools) {

            this.pools = pools;
            return this;
        }
        public Builder pools(PoolStatusPatch... pools) {
            return pools(List.of(pools));
        }
        public ResourcePoolStatusRequestStatusPatch build() {
            final var _resultValue = new ResourcePoolStatusRequestStatusPatch();
            _resultValue.conditions = conditions;
            _resultValue.poolCount = poolCount;
            _resultValue.pools = pools;
            return _resultValue;
        }
    }
}
