// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.core.v1.outputs;

import com.pulumi.core.Either;
import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TCPSocketActionPatch {
    /**
     * @return Optional: Host name to connect to, defaults to the pod IP.
     * 
     */
    private @Nullable String host;
    /**
     * @return Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
     * 
     */
    private @Nullable Either<Integer,String> port;

    private TCPSocketActionPatch() {}
    /**
     * @return Optional: Host name to connect to, defaults to the pod IP.
     * 
     */
    public Optional<String> host() {
        return Optional.ofNullable(this.host);
    }
    /**
     * @return Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
     * 
     */
    public Optional<Either<Integer,String>> port() {
        return Optional.ofNullable(this.port);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TCPSocketActionPatch defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String host;
        private @Nullable Either<Integer,String> port;
        public Builder() {}
        public Builder(TCPSocketActionPatch defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.host = defaults.host;
    	      this.port = defaults.port;
        }

        @CustomType.Setter
        public Builder host(@Nullable String host) {

            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable Either<Integer,String> port) {

            this.port = port;
            return this;
        }
        public TCPSocketActionPatch build() {
            final var _resultValue = new TCPSocketActionPatch();
            _resultValue.host = host;
            _resultValue.port = port;
            return _resultValue;
        }
    }
}
