name: Download SDK
description: Downloads and extracts SDK artifacts for a specific language

inputs:
  language:
    description: 'The SDK language to download (nodejs, python, dotnet, java)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download SDK
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ inputs.language }}-sdk.tar.gz
        path: ${{ github.workspace }}/sdk/

    - name: UnTar SDK folder
      shell: bash
      run: tar -zxf ${{ github.workspace }}/sdk/${{ inputs.language }}.tar.gz -C ${{ github.workspace }}/sdk/${{ inputs.language }}
