// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Certificates.V1
{

    /// <summary>
    /// CertificateSigningRequestCondition describes a condition of a CertificateSigningRequest object
    /// </summary>
    public class CertificateSigningRequestConditionArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// lastTransitionTime is the time the condition last transitioned from one status to another. If unset, when a new condition type is added or an existing condition's status is changed, the server defaults this to the current time.
        /// </summary>
        [Input("lastTransitionTime")]
        public Input<string>? LastTransitionTime { get; set; }

        /// <summary>
        /// lastUpdateTime is the time of the last update to this condition
        /// </summary>
        [Input("lastUpdateTime")]
        public Input<string>? LastUpdateTime { get; set; }

        /// <summary>
        /// message contains a human readable message with details about the request state
        /// </summary>
        [Input("message")]
        public Input<string>? Message { get; set; }

        /// <summary>
        /// reason indicates a brief reason for the request state
        /// </summary>
        [Input("reason")]
        public Input<string>? Reason { get; set; }

        /// <summary>
        /// status of the condition, one of True, False, Unknown. Approved, Denied, and Failed conditions may not be "False" or "Unknown".
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        /// <summary>
        /// type of the condition. Known conditions are "Approved", "Denied", and "Failed".
        /// 
        /// An "Approved" condition is added via the /approval subresource, indicating the request was approved and should be issued by the signer.
        /// 
        /// A "Denied" condition is added via the /approval subresource, indicating the request was denied and should not be issued by the signer.
        /// 
        /// A "Failed" condition is added via the /status subresource, indicating the signer failed to issue the certificate.
        /// 
        /// Approved and Denied conditions are mutually exclusive. Approved, Denied, and Failed conditions cannot be removed once added.
        /// 
        /// Only one condition of a given type is allowed.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public CertificateSigningRequestConditionArgs()
        {
        }
    }
}
