// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.ApiRegistration.V1Beta1
{

    /// <summary>
    /// APIServiceStatus contains derived information about an API server
    /// 
    /// By default Pulumi does _not_ wait for this resource to
    /// become ready when it is created or updated.
    /// 
    /// If you want Pulumi to wait for this resource to become ready, you can use the
    /// 'pulumi.com/waitFor' annotation to provide custom readiness criteria. See the
    /// documentation
    /// (http://localhost:1313/registry/packages/kubernetes/installation-configuration/#pulumicomwaitfor)
    /// for a detailed description of the values this annotation accepts.
    /// </summary>
    [OutputType]
    public sealed class APIServiceStatusPatch
    {
        /// <summary>
        /// Current service state of apiService.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ApiRegistration.V1Beta1.APIServiceConditionPatch> Conditions;

        [OutputConstructor]
        private APIServiceStatusPatch(ImmutableArray<Pulumi.Kubernetes.Types.Outputs.ApiRegistration.V1Beta1.APIServiceConditionPatch> conditions)
        {
            Conditions = conditions;
        }
    }
}
