// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.resource.v1beta2.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CapacityRequestPolicyRange {
    /**
     * @return Max defines the upper limit for capacity that can be requested.
     * 
     * Max must be less than or equal to the capacity value. Min and requestPolicy.default must be less than or equal to the maximum.
     * 
     */
    private @Nullable String max;
    /**
     * @return Min specifies the minimum capacity allowed for a consumption request.
     * 
     * Min must be greater than or equal to zero, and less than or equal to the capacity value. requestPolicy.default must be more than or equal to the minimum.
     * 
     */
    private String min;
    /**
     * @return Step defines the step size between valid capacity amounts within the range.
     * 
     * Max (if set) and requestPolicy.default must be a multiple of Step. Min + Step must be less than or equal to the capacity value.
     * 
     */
    private @Nullable String step;

    private CapacityRequestPolicyRange() {}
    /**
     * @return Max defines the upper limit for capacity that can be requested.
     * 
     * Max must be less than or equal to the capacity value. Min and requestPolicy.default must be less than or equal to the maximum.
     * 
     */
    public Optional<String> max() {
        return Optional.ofNullable(this.max);
    }
    /**
     * @return Min specifies the minimum capacity allowed for a consumption request.
     * 
     * Min must be greater than or equal to zero, and less than or equal to the capacity value. requestPolicy.default must be more than or equal to the minimum.
     * 
     */
    public String min() {
        return this.min;
    }
    /**
     * @return Step defines the step size between valid capacity amounts within the range.
     * 
     * Max (if set) and requestPolicy.default must be a multiple of Step. Min + Step must be less than or equal to the capacity value.
     * 
     */
    public Optional<String> step() {
        return Optional.ofNullable(this.step);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CapacityRequestPolicyRange defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String max;
        private String min;
        private @Nullable String step;
        public Builder() {}
        public Builder(CapacityRequestPolicyRange defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.max = defaults.max;
    	      this.min = defaults.min;
    	      this.step = defaults.step;
        }

        @CustomType.Setter
        public Builder max(@Nullable String max) {

            this.max = max;
            return this;
        }
        @CustomType.Setter
        public Builder min(String min) {
            if (min == null) {
              throw new MissingRequiredPropertyException("CapacityRequestPolicyRange", "min");
            }
            this.min = min;
            return this;
        }
        @CustomType.Setter
        public Builder step(@Nullable String step) {

            this.step = step;
            return this;
        }
        public CapacityRequestPolicyRange build() {
            final var _resultValue = new CapacityRequestPolicyRange();
            _resultValue.max = max;
            _resultValue.min = min;
            _resultValue.step = step;
            return _resultValue;
        }
    }
}
