// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.resource.v1.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.kubernetes.resource.v1.outputs.Counter;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DeviceCounterConsumptionPatch {
    /**
     * @return CounterSet is the name of the set from which the counters defined will be consumed.
     * 
     */
    private @Nullable String counterSet;
    /**
     * @return Counters defines the counters that will be consumed by the device.
     * 
     * The maximum number counters in a device is 32. In addition, the maximum number of all counters in all devices is 1024 (for example, 64 devices with 16 counters each).
     * 
     */
    private @Nullable Map<String,Counter> counters;

    private DeviceCounterConsumptionPatch() {}
    /**
     * @return CounterSet is the name of the set from which the counters defined will be consumed.
     * 
     */
    public Optional<String> counterSet() {
        return Optional.ofNullable(this.counterSet);
    }
    /**
     * @return Counters defines the counters that will be consumed by the device.
     * 
     * The maximum number counters in a device is 32. In addition, the maximum number of all counters in all devices is 1024 (for example, 64 devices with 16 counters each).
     * 
     */
    public Map<String,Counter> counters() {
        return this.counters == null ? Map.of() : this.counters;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DeviceCounterConsumptionPatch defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String counterSet;
        private @Nullable Map<String,Counter> counters;
        public Builder() {}
        public Builder(DeviceCounterConsumptionPatch defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.counterSet = defaults.counterSet;
    	      this.counters = defaults.counters;
        }

        @CustomType.Setter
        public Builder counterSet(@Nullable String counterSet) {

            this.counterSet = counterSet;
            return this;
        }
        @CustomType.Setter
        public Builder counters(@Nullable Map<String,Counter> counters) {

            this.counters = counters;
            return this;
        }
        public DeviceCounterConsumptionPatch build() {
            final var _resultValue = new DeviceCounterConsumptionPatch();
            _resultValue.counterSet = counterSet;
            _resultValue.counters = counters;
            return _resultValue;
        }
    }
}
