#!/bin/bash
set -e

# Skip the config file name argument.
shift

cat <<EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: $1
data:
  pwd: $PWD
  kustomize_plugin_home: $KUSTOMIZE_PLUGIN_HOME
  kustomize_plugin_config_root: $KUSTOMIZE_PLUGIN_CONFIG_ROOT
EOF