name: Setup Tools
description: Installs all tools (Go, Node, Python, .NET, Java, Pulumi, etc.) using mise

inputs:
  cache:
    description: Enable caching
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3
      with:
        # Latest working version. See https://github.com/jdx/mise/discussions/6781
        version: 2025.10.16
        github_token: ${{ github.token }}
        cache_key: "mise-{{platform}}-{{file_hash}}"
        cache_save: ${{ inputs.cache }}

    - name: Setup Go Cache
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ env.GOVERSION }}
        cache-dependency-path: "**/*.sum"
        cache: ${{ inputs.cache }}
