name: Setup Tools
description: Installs all tools (Go, Node, Python, .NET, Java, Pulumi, etc.) using mise

inputs:
  cache:
    description: Enable caching
    required: false
    default: "false"
  github_token:
    description: GitHub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: blampe/mise-action@blampe/plugins
      env:
        MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
      with:
        version: 2025.11.6
        cache_save: ${{ inputs.cache }}
        github_token: ${{ inputs.github_token }}
        plugin_install: https://github.com/pulumi/vfox-pulumi

    - name: Setup Go Cache
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        cache: ${{ inputs.cache }}
        cache-dependency-path: |
          provider/*.sum
          upstream/*.sum
          sdk/go/*.sum
          sdk/*.sum
          *.sum

    - name: Setup Node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        # we don't set node-version because we install with mise.
        # this step is needed to setup npm auth
        registry-url: https://registry.npmjs.org
