// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.meta.v1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


/**
 * GroupResource specifies a Group and a Resource, but does not force a version.  This is useful for identifying concepts during lookup stages without having partially valid types
 * 
 */
public final class GroupResourceArgs extends com.pulumi.resources.ResourceArgs {

    public static final GroupResourceArgs Empty = new GroupResourceArgs();

    @Import(name="group", required=true)
    private Output<String> group;

    public Output<String> group() {
        return this.group;
    }

    @Import(name="resource", required=true)
    private Output<String> resource;

    public Output<String> resource() {
        return this.resource;
    }

    private GroupResourceArgs() {}

    private GroupResourceArgs(GroupResourceArgs $) {
        this.group = $.group;
        this.resource = $.resource;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GroupResourceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GroupResourceArgs $;

        public Builder() {
            $ = new GroupResourceArgs();
        }

        public Builder(GroupResourceArgs defaults) {
            $ = new GroupResourceArgs(Objects.requireNonNull(defaults));
        }

        public Builder group(Output<String> group) {
            $.group = group;
            return this;
        }

        public Builder group(String group) {
            return group(Output.of(group));
        }

        public Builder resource(Output<String> resource) {
            $.resource = resource;
            return this;
        }

        public Builder resource(String resource) {
            return resource(Output.of(resource));
        }

        public GroupResourceArgs build() {
            if ($.group == null) {
                throw new MissingRequiredPropertyException("GroupResourceArgs", "group");
            }
            if ($.resource == null) {
                throw new MissingRequiredPropertyException("GroupResourceArgs", "resource");
            }
            return $;
        }
    }

}
