// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Resource.V1Beta1
{

    /// <summary>
    /// CapacityRequestPolicyRange defines a valid range for consumable capacity values.
    /// 
    ///   - If the requested amount is less than Min, it is rounded up to the Min value.
    ///   - If Step is set and the requested amount is between Min and Max but not aligned with Step,
    ///     it will be rounded up to the next value equal to Min + (n * Step).
    ///   - If Step is not set, the requested amount is used as-is if it falls within the range Min to Max (if set).
    ///   - If the requested or rounded amount exceeds Max (if set), the request does not satisfy the policy,
    ///     and the device cannot be allocated.
    /// </summary>
    [OutputType]
    public sealed class CapacityRequestPolicyRange
    {
        /// <summary>
        /// Max defines the upper limit for capacity that can be requested.
        /// 
        /// Max must be less than or equal to the capacity value. Min and requestPolicy.default must be less than or equal to the maximum.
        /// </summary>
        public readonly string Max;
        /// <summary>
        /// Min specifies the minimum capacity allowed for a consumption request.
        /// 
        /// Min must be greater than or equal to zero, and less than or equal to the capacity value. requestPolicy.default must be more than or equal to the minimum.
        /// </summary>
        public readonly string Min;
        /// <summary>
        /// Step defines the step size between valid capacity amounts within the range.
        /// 
        /// Max (if set) and requestPolicy.default must be a multiple of Step. Min + Step must be less than or equal to the capacity value.
        /// </summary>
        public readonly string Step;

        [OutputConstructor]
        private CapacityRequestPolicyRange(
            string max,

            string min,

            string step)
        {
            Max = max;
            Min = min;
            Step = step;
        }
    }
}
