// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Core.V1
{

    /// <summary>
    /// PodVolumeHealth contains health information for a volume used by a pod, reported by the CSI node plugin via the kubelet.
    /// </summary>
    [OutputType]
    public sealed class PodVolumeHealthPatch
    {
        /// <summary>
        /// conditions is the set of adverse conditions reported by the CSI node plugin for this volume on this node. At most 16 conditions may be reported.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Core.V1.VolumeHealthConditionPatch> HealthConditions;
        /// <summary>
        /// lastTransitionTime is when the current set of conditions first appeared.
        /// </summary>
        public readonly string LastTransitionTime;
        /// <summary>
        /// name matches an entry in pod.spec.volumes.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private PodVolumeHealthPatch(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Core.V1.VolumeHealthConditionPatch> healthConditions,

            string lastTransitionTime,

            string name)
        {
            HealthConditions = healthConditions;
            LastTransitionTime = lastTransitionTime;
            Name = name;
        }
    }
}
