// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Resource.V1Alpha3
{

    /// <summary>
    /// DeviceCounterConsumption defines a set of counters that a device will consume from a CounterSet.
    /// </summary>
    public class DeviceCounterConsumptionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CounterSet defines the set from which the counters defined will be consumed.
        /// </summary>
        [Input("counterSet", required: true)]
        public Input<string> CounterSet { get; set; } = null!;

        [Input("counters", required: true)]
        private InputMap<Pulumi.Kubernetes.Types.Inputs.Resource.V1Alpha3.CounterArgs>? _counters;

        /// <summary>
        /// Counters defines the Counter that will be consumed by the device.
        /// 
        /// The maximum number counters in a device is 32. In addition, the maximum number of all counters in all devices is 1024 (for example, 64 devices with 16 counters each).
        /// </summary>
        public InputMap<Pulumi.Kubernetes.Types.Inputs.Resource.V1Alpha3.CounterArgs> Counters
        {
            get => _counters ?? (_counters = new InputMap<Pulumi.Kubernetes.Types.Inputs.Resource.V1Alpha3.CounterArgs>());
            set => _counters = value;
        }

        public DeviceCounterConsumptionArgs()
        {
        }
        public static new DeviceCounterConsumptionArgs Empty => new DeviceCounterConsumptionArgs();
    }
}
