// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.core.v1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * ContainerStateWaiting is a waiting state of a container.
 * 
 */
public final class ContainerStateWaitingArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContainerStateWaitingArgs Empty = new ContainerStateWaitingArgs();

    /**
     * Message regarding why the container is not yet running.
     * 
     */
    @Import(name="message")
    private @Nullable Output<String> message;

    /**
     * @return Message regarding why the container is not yet running.
     * 
     */
    public Optional<Output<String>> message() {
        return Optional.ofNullable(this.message);
    }

    /**
     * (brief) reason the container is not yet running.
     * 
     */
    @Import(name="reason")
    private @Nullable Output<String> reason;

    /**
     * @return (brief) reason the container is not yet running.
     * 
     */
    public Optional<Output<String>> reason() {
        return Optional.ofNullable(this.reason);
    }

    private ContainerStateWaitingArgs() {}

    private ContainerStateWaitingArgs(ContainerStateWaitingArgs $) {
        this.message = $.message;
        this.reason = $.reason;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerStateWaitingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerStateWaitingArgs $;

        public Builder() {
            $ = new ContainerStateWaitingArgs();
        }

        public Builder(ContainerStateWaitingArgs defaults) {
            $ = new ContainerStateWaitingArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param message Message regarding why the container is not yet running.
         * 
         * @return builder
         * 
         */
        public Builder message(@Nullable Output<String> message) {
            $.message = message;
            return this;
        }

        /**
         * @param message Message regarding why the container is not yet running.
         * 
         * @return builder
         * 
         */
        public Builder message(String message) {
            return message(Output.of(message));
        }

        /**
         * @param reason (brief) reason the container is not yet running.
         * 
         * @return builder
         * 
         */
        public Builder reason(@Nullable Output<String> reason) {
            $.reason = reason;
            return this;
        }

        /**
         * @param reason (brief) reason the container is not yet running.
         * 
         * @return builder
         * 
         */
        public Builder reason(String reason) {
            return reason(Output.of(reason));
        }

        public ContainerStateWaitingArgs build() {
            return $;
        }
    }

}
