// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.core.v1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


/**
 * PodSchedulingGate is associated to a Pod to guard its scheduling.
 * 
 */
public final class PodSchedulingGateArgs extends com.pulumi.resources.ResourceArgs {

    public static final PodSchedulingGateArgs Empty = new PodSchedulingGateArgs();

    /**
     * Name of the scheduling gate. Each scheduling gate must have a unique name field.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the scheduling gate. Each scheduling gate must have a unique name field.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private PodSchedulingGateArgs() {}

    private PodSchedulingGateArgs(PodSchedulingGateArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PodSchedulingGateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PodSchedulingGateArgs $;

        public Builder() {
            $ = new PodSchedulingGateArgs();
        }

        public Builder(PodSchedulingGateArgs defaults) {
            $ = new PodSchedulingGateArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Name of the scheduling gate. Each scheduling gate must have a unique name field.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the scheduling gate. Each scheduling gate must have a unique name field.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public PodSchedulingGateArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("PodSchedulingGateArgs", "name");
            }
            return $;
        }
    }

}
