// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.kubernetes.core.v1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * VolumeHealthCondition represents an adverse health condition reported for a volume.
 * 
 */
public final class VolumeHealthConditionPatchArgs extends com.pulumi.resources.ResourceArgs {

    public static final VolumeHealthConditionPatchArgs Empty = new VolumeHealthConditionPatchArgs();

    /**
     * message is a human-readable description. Maximum permitted length of a message is 1024 bytes.
     * 
     */
    @Import(name="message")
    private @Nullable Output<String> message;

    /**
     * @return message is a human-readable description. Maximum permitted length of a message is 1024 bytes.
     * 
     */
    public Optional<Output<String>> message() {
        return Optional.ofNullable(this.message);
    }

    /**
     * reason is a brief CamelCase machine-parseable reason. Together with status it forms the unique identity of a condition entry. Maximum permitted length of a reason is 256 bytes.
     * 
     */
    @Import(name="reason")
    private @Nullable Output<String> reason;

    /**
     * @return reason is a brief CamelCase machine-parseable reason. Together with status it forms the unique identity of a condition entry. Maximum permitted length of a reason is 256 bytes.
     * 
     */
    public Optional<Output<String>> reason() {
        return Optional.ofNullable(this.reason);
    }

    /**
     * status is the machine-parseable health category. Possible values: - &#34;Inaccessible&#34;: the volume cannot be accessed. - &#34;DataLoss&#34;: data loss has been detected on the volume. - &#34;Degraded&#34;: the volume is functioning with reduced capability.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return status is the machine-parseable health category. Possible values: - &#34;Inaccessible&#34;: the volume cannot be accessed. - &#34;DataLoss&#34;: data loss has been detected on the volume. - &#34;Degraded&#34;: the volume is functioning with reduced capability.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    private VolumeHealthConditionPatchArgs() {}

    private VolumeHealthConditionPatchArgs(VolumeHealthConditionPatchArgs $) {
        this.message = $.message;
        this.reason = $.reason;
        this.status = $.status;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VolumeHealthConditionPatchArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VolumeHealthConditionPatchArgs $;

        public Builder() {
            $ = new VolumeHealthConditionPatchArgs();
        }

        public Builder(VolumeHealthConditionPatchArgs defaults) {
            $ = new VolumeHealthConditionPatchArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param message message is a human-readable description. Maximum permitted length of a message is 1024 bytes.
         * 
         * @return builder
         * 
         */
        public Builder message(@Nullable Output<String> message) {
            $.message = message;
            return this;
        }

        /**
         * @param message message is a human-readable description. Maximum permitted length of a message is 1024 bytes.
         * 
         * @return builder
         * 
         */
        public Builder message(String message) {
            return message(Output.of(message));
        }

        /**
         * @param reason reason is a brief CamelCase machine-parseable reason. Together with status it forms the unique identity of a condition entry. Maximum permitted length of a reason is 256 bytes.
         * 
         * @return builder
         * 
         */
        public Builder reason(@Nullable Output<String> reason) {
            $.reason = reason;
            return this;
        }

        /**
         * @param reason reason is a brief CamelCase machine-parseable reason. Together with status it forms the unique identity of a condition entry. Maximum permitted length of a reason is 256 bytes.
         * 
         * @return builder
         * 
         */
        public Builder reason(String reason) {
            return reason(Output.of(reason));
        }

        /**
         * @param status status is the machine-parseable health category. Possible values: - &#34;Inaccessible&#34;: the volume cannot be accessed. - &#34;DataLoss&#34;: data loss has been detected on the volume. - &#34;Degraded&#34;: the volume is functioning with reduced capability.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status status is the machine-parseable health category. Possible values: - &#34;Inaccessible&#34;: the volume cannot be accessed. - &#34;DataLoss&#34;: data loss has been detected on the volume. - &#34;Degraded&#34;: the volume is functioning with reduced capability.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        public VolumeHealthConditionPatchArgs build() {
            return $;
        }
    }

}
