// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.FlowControl.V1
{

    /// <summary>
    /// Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
    /// </summary>
    public class SubjectPatchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// `group` matches based on user group name.
        /// </summary>
        [Input("group")]
        public Input<Pulumi.Kubernetes.Types.Inputs.FlowControl.V1.GroupSubjectPatchArgs>? Group { get; set; }

        /// <summary>
        /// `kind` indicates which one of the other fields is non-empty. Required
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// `serviceAccount` matches ServiceAccounts.
        /// </summary>
        [Input("serviceAccount")]
        public Input<Pulumi.Kubernetes.Types.Inputs.FlowControl.V1.ServiceAccountSubjectPatchArgs>? ServiceAccount { get; set; }

        /// <summary>
        /// `user` matches based on username.
        /// </summary>
        [Input("user")]
        public Input<Pulumi.Kubernetes.Types.Inputs.FlowControl.V1.UserSubjectPatchArgs>? User { get; set; }

        public SubjectPatchArgs()
        {
        }
        public static new SubjectPatchArgs Empty => new SubjectPatchArgs();
    }
}
