name: pull-request
"on":
  pull_request_target:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOLANGCI_LINT_VERSION: v1.31
  GOLANGCI_LINT_TIMEOUT: 10m

jobs:
  comment-on-pr:
    # We only care about commenting on a PR if the PR is from a fork
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            PR is now waiting for a maintainer to run the acceptance tests. This PR will only perform build and linting.

            **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint-provider-pkg
        uses: golangci/golangci-lint-action@v1
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: -c ../../.golangci.yml --timeout ${{ env.GOLANGCI_LINT_TIMEOUT }}
          working-directory: provider/pkg
