name: pull-request
on:
  pull_request_target: {}
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  PROVIDER: kubernetes
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  TRAVIS_OS_NAME: linux
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  AWS_REGION: us-west-2
  PULUMI_TEST_OWNER: moolumi
  GOLANGCI_LINT_VERSION: v1.46.2
  GOLANGCI_LINT_TIMEOUT: 10m
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    name: comment-on-pr
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: >
          PR is now waiting for a maintainer to run the acceptance tests.

          **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event.pull_request.head.repo.full_name != github.repository
