name: pull-request
"on":
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOLANGCI_LINT_VERSION: v1.31
  GOLANGCI_LINT_TIMEOUT: 10m

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            PR is now waiting for a maintainer to run the acceptance tests. This PR will only perform build and linting.

            **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint-provider-pkg
        uses: golangci/golangci-lint-action@v1
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: -c ../../.golangci.yml --timeout ${{ env.GOLANGCI_LINT_TIMEOUT }}
          working-directory: provider/pkg
  prerequisities:
    name: build-provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@release/v1-alpha
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1
      - name: Build K8sgen
        run: make k8sgen
      - name: Prepare openapi file
        run: make openapi_file
      - name: Prepare Schema
        run: make schema
      - name: Make Kubernetes Provider
        run: make k8sprovider
      - name: Test provider
        run: make test_provider

