# From https://kubernetes.io/docs/concepts/workloads/pods/#using-pods
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
